services:
  - type: web
    name: pgb2-report-sender
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    pythonVersion: 3.10.0
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: PGB2_BASE_URL
        sync: false
      - key: PGB2_CLIENT_ID
        sync: false
      - key: PGB2_CLIENT_SECRET
        sync: false
      - key: PGB2_USERNAME
        sync: false
      - key: PGB2_PASSWORD
        sync: false
      - key: MWE_ID
        sync: false
      - key: EXCEL_PATH
        value: SOGLbazaraportTAURON.xlsx